# Generated by Django 3.0.5 on 2020-12-17 22:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegefest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='compitition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('club', models.CharField(default=False, max_length=15)),
                ('desc', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('club', models.CharField(default=False, max_length=15)),
                ('desc', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('club', models.CharField(default=False, max_length=15)),
                ('desc', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('club', models.CharField(default=False, max_length=15)),
                ('desc', models.TextField(max_length=150)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
    ]
