# Generated by Django 3.0.5 on 2020-12-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collegefest',
        ),
        migrations.DeleteModel(
            name='compitition',
        ),
        migrations.DeleteModel(
            name='hackathon',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.DeleteModel(
            name='workshop',
        ),
    ]
