# Generated by Django 3.0.5 on 2020-12-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
