# Generated by Django 3.0.5 on 2020-12-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_adminreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='branch',
            field=models.CharField(max_length=50),
        ),
    ]
