# Generated by Django 3.0.5 on 2020-12-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='adminreg',
            name='password1',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminreg',
            name='password2',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
    ]
