# Generated by Django 3.1.4 on 2020-12-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201224_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreg',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='phone',
        ),
        migrations.AddField(
            model_name='userreg',
            name='password1',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='password2',
            field=models.CharField(default='NULL', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreg',
            name='username',
            field=models.CharField(default='NULL', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
