# Generated by Django 3.1.4 on 2020-12-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_login_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminreg',
            old_name='club_name',
            new_name='club',
        ),
    ]
