# Generated by Django 3.1.4 on 2021-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201227_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='login_user',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
