# Generated by Django 3.0.5 on 2021-01-16 18:55

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210115_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='password1',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='password2',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password1',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password2',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=10)),
        ),
    ]
