# Generated by Django 3.0.5 on 2021-01-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210117_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='password1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='password2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='password2',
            field=models.CharField(max_length=10),
        ),
    ]
