# Generated by Django 2.2.8 on 2021-01-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210117_0029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
