# Generated by Django 2.1.7 on 2021-02-17 18:34

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210117_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreg',
            name='password1',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='adminreg',
            name='password2',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
