# Generated by Django 2.1.7 on 2021-02-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210218_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregmodel',
            name='desc',
            field=models.TextField(default='NULL', max_length=1000),
        ),
    ]
