# Generated by Django 3.0.5 on 2020-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegefest',
            name='college_name',
            field=models.CharField(default='NIE', max_length=20),
            preserve_default=False,
        ),
    ]
