# Generated by Django 3.1.4 on 2020-12-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_collegefest_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegefest',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='compitition',
            name='club',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='compitition',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='club',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='club',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='club',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
