# Generated by Django 3.1.4 on 2021-01-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20201226_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=50)),
                ('title_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='collegefest',
        ),
        migrations.DeleteModel(
            name='compitition',
        ),
        migrations.DeleteModel(
            name='hackathon',
        ),
        migrations.DeleteModel(
            name='quiz',
        ),
        migrations.DeleteModel(
            name='workshop',
        ),
    ]
